grid_map_topic: /l3/terrain_model/terrain_model_map

grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
      layer: elevation

  - name: map_region
    type: map_region
    params:
      color: 3289650
      line_width: 0.003

  - name: elevation_grid
    type: occupancy_grid
    params:
      layer: elevation
      data_min: 0.08
      data_max: -0.16

  - name: surface_normals
    type: vectors
    params:
      layer_prefix: normal_
      position_layer: elevation
      scale: 0.06
      line_width: 0.002
      color: 16777215 # white